//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Details
    {
        public int C_ID { get; set; }
        public string Firm_Name { get; set; }
        public string Contact_Person_Name { get; set; }
        public string Email_ID { get; set; }
        public Nullable<int> Mobile_No { get; set; }
    }
}
