//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Details
    {
        public int M_ID { get; set; }
        public string Client_Name { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string Note { get; set; }
        public int ID { get; set; }
    
        public virtual UserAdmin UserAdmin { get; set; }
    }
}
