//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
       
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public string Email_ID { get; set; }
        public string Mobile_No { get; set; }
        public string Address { get; set; }
        public string Role { get; set; }
        public string Password { get; set; }

        public UserAdmin()
        {
            Date = DateTime.Now;
            this.Meeting_Details = new HashSet<Meeting_Details>();
            this.Attendence2 = new HashSet<Attendence2>();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_Details> Meeting_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendence2> Attendence2 { get; set; }
    }
}
